# Generated by Django 4.2.6 on 2023-10-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('type', models.CharField(choices=[('Cheap', 'Cheap'), ('Comfortable', 'Comfortable'), ('V.I.P.', 'V.I.P.')], max_length=255)),
                ('reserved', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.comment')),
            ],
        ),
        migrations.CreateModel(
            name='BookApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_persons', models.IntegerField()),
                ('start_book', models.DateField()),
                ('end_book', models.DateField()),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('approve_status', models.BooleanField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.client')),
                ('room_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.room')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.service')),
            ],
        ),
    ]
