# Generated by Django 4.2.6 on 2023-10-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookapplication',
            name='services',
        ),
        migrations.AddField(
            model_name='bookapplication',
            name='services',
            field=models.ManyToManyField(to='admin_app.service'),
        ),
    ]
