# Generated by Django 4.2.6 on 2023-10-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_bookapplication_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.comment'),
        ),
    ]
